[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_interval = 750

[font]
size = 10.0

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "hack"
style = "Bold Italic"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[terminal]

[terminal.shell]
program = "/usr/bin/fish"
args = ["--login"]

[colors.primary]
background = '#232326'
foreground = '#ffffff'
